/**
 * Termux server code - minified single-line for easy copy-paste in Termux.
 * This file is NOT imported by app code, it's a reference for the setup guide.
 *
 * Usage in Termux:
 *   node -e "require('http').createServer(...).listen(2324,...)"
 *
 * Full command (copy this into Termux):
 */
export const SERVER_START_COMMAND = `node -e "require('http').createServer((r,q)=>{const{execSync:e}=require('child_process');const{f:g,w:h,x:i,m:j,readdirSync:k,statSync:l,rmSync:m,writeFileSync:n}=require('fs');const{resolve:o,dirname:p,join:q1}=require('path');const H=process.env.HOME;q.setHeader('Access-Control-Allow-Origin','*');const T=r.headers['x-auth-token'];if(T!==(global.TOKEN||(global.TOKEN=require('crypto').randomBytes(16).toString('hex')))){q.writeHead(401);q.end();return}n(H+'/.xiaoye-token',global.TOKEN);const u=new URL(r.url,'http://l:2324');const U=t=>t.replace(/^~/,H);try{if(u.pathname==='/ping'){q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({status:'ok'}));return}if(u.pathname==='/exec'&&r.method==='POST'){let b='';r.on('data',c=>b+=c);r.on('end',()=>{try{const d=JSON.parse(b);const o=e(d.command,{cwd:d.cwd?U(d.cwd):H,timeout:d.timeout||3e4,encoding:'utf-8',maxBuffer:10485760});q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({stdout:o,stderr:'',exitCode:0}))}catch(e){q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({stdout:e.stdout||'',stderr:e.stderr||'',exitCode:e.code||1}))}});return}const P=U(u.searchParams.get('path')||'');if(u.pathname==='/fs/list'){try{const i=k(P).map(n=>{try{const s=l(q1(P,n));return{name:n,path:q1(P,n),isDirectory:s.isDirectory(),size:s.size,modifiedAt:s.mtime.toISOString()}}catch{return null}}).filter(Boolean);q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({files:i}));return}catch(e){q.writeHead(500);q.end();return}}if(u.pathname==='/fs/read'){if(i(P)){q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({content:g(P,'utf-8')}))}else{q.writeHead(404);q.end()}return}if(u.pathname==='/fs/write'&&r.method==='POST'){let b='';r.on('data',c=>b+=c);r.on('end',()=>{const d=JSON.parse(b);const P1=U(d.path);j(o(P1),{recursive:true});h(P1,d.content,'utf-8');q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({success:true}))});return}if(u.pathname==='/fs/delete'&&r.method==='DELETE'){if(i(P))m(P,{recursive:true,force:true});q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({success:true}));return}if(u.pathname==='/fs/mkdir'&&r.method==='POST'){let b='';r.on('data',c=>b+=c);r.on('end',()=>{j(U(JSON.parse(b).path),{recursive:true});q.writeHead(200,{'Content-Type':'application/json'});q.end(JSON.stringify({success:true}))});return}q.writeHead(404);q.end()}catch(e){q.writeHead(500);q.end(JSON.stringify({error:e.message}))}}).listen(2324,'0.0.0.0',()=>{console.log('Node server running on port 2324')})"`

/**
 * Simplified commands shown to the user in the setup guide
 */
export const SIMPLE_SETUP_COMMANDS = [
  {
    step: 1,
    label: '安装 Node.js',
    command: 'pkg update -y && pkg upgrade -y\npkg install nodejs -y',
  },
  {
    step: 2,
    label: '启动服务器（一行命令）',
    command: 'node -e "require(\'http\').createServer((r,q)=>{q.setHeader(\'Access-Control-Allow-Origin\',\'*\');const T=r.headers[\'x-auth-token\'];if(T!==(global.TOKEN||(global.TOKEN=require(\'crypto\').randomBytes(16).toString(\'hex\')))){q.writeHead(401);q.end();return}require(\'fs\').writeFileSync(require(\'os\').homedir()+\'/.xiaoye-token\',global.TOKEN);try{const{execSync:e}=require(\'child_process\'),{readFileSync:f,writeFileSync:w,existsSync:x,mkdirSync:m,readdirSync:d,statSync:s,rmSync:u}=require(\'fs\'),{resolve:a,dirname:o,join:p}=require(\'path\'),H=require(\'os\').homedir(),U=t=>t.replace(/^~/,H),nu=new URL(r.url,\'http://l:2324\');if(nu.pathname===\'/ping\'){q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({status:\'ok\'}));return}if(nu.pathname===\'/exec\'&&r.method===\'POST\'){let b=\'\';r.on(\'data\',c=>b+=c);r.on(\'end\',()=>{try{const d=JSON.parse(b),o=e(d.command,{cwd:d.cwd?U(d.cwd):H,timeout:d.timeout||3e4,encoding:\'utf-8\',maxBuffer:10485760});q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({stdout:o,stderr:\'\',exitCode:0}))}catch(e){q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({stdout:e.stdout||\'\',stderr:e.stderr||\'\',exitCode:e.code||1}))}});return}const P=U(nu.searchParams.get(\'path\')||\'\');if(nu.pathname===\'/fs/list\'){try{const i=d(P).map(n=>{try{const s=s(p(P,n));return{name:n,path:p(P,n),isDirectory:s.isDirectory(),size:s.size,modifiedAt:s.mtime.toISOString()}}catch{return null}}).filter(Boolean);q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({files:i}));return}catch(e){q.writeHead(500);q.end();return}}if(nu.pathname===\'/fs/read\'){if(x(P)){q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({content:f(P,\'utf-8\')}))}else{q.writeHead(404);q.end()}return}if(nu.pathname===\'/fs/write\'&&r.method===\'POST\'){let b=\'\';r.on(\'data\',c=>b+=c);r.on(\'end\',()=>{const d=JSON.parse(b),P1=U(d.path);m(o(P1),{recursive:true});w(P1,d.content,\'utf-8\');q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({success:true}))});return}if(nu.pathname===\'/fs/delete\'&&r.method===\'DELETE\'){if(x(P))u(P,{recursive:true,force:true});q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({success:true}));return}if(nu.pathname===\'/fs/mkdir\'&&r.method===\'POST\'){let b=\'\';r.on(\'data\',c=>b+=c);r.on(\'end\',()=>{m(U(JSON.parse(b).path),{recursive:true});q.writeHead(200,{\'Content-Type\':\'application/json\'});q.end(JSON.stringify({success:true}))});return}q.writeHead(404);q.end()}catch(e){q.writeHead(500);q.end(JSON.stringify({error:e.message}))}}).listen(2324,\'0.0.0.0\',()=>console.log(\'Server ready\'))"',
  },
]
